//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace drugaApka.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXPENSES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EXPENSES()
        {
            this.USERS_EXPENSES = new HashSet<USERS_EXPENSES>();
        }
    
        public int EXPENSE_ID { get; set; }
        public Nullable<float> RentalFee { get; set; }
        public Nullable<float> Rent { get; set; }
        public Nullable<float> CurrentBill { get; set; }
        public Nullable<float> GasBill { get; set; }
        public Nullable<float> InternetBill { get; set; }
        public System.DateTime ExpenseDate { get; set; }
        public string ExpensePerMonth { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USERS_EXPENSES> USERS_EXPENSES { get; set; }
        public virtual EXTRA_EXPENSES EXTRA_EXPENSES { get; set; }
    }
}
