//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace drugaApka.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAYS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PAYS()
        {
            this.BALANCES = new HashSet<BALANCES>();
        }
    
        public int PAY_ID { get; set; }
        public System.DateTime date { get; set; }
        public double Value { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BALANCES> BALANCES { get; set; }
        public virtual USERS USERS { get; set; }
    }
}
