//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace drugaApka.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RentFlatModelContainer : DbContext
    {
        public RentFlatModelContainer()
            : base("name=RentFlatConnectionString")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BALANCES> BALANCESSet { get; set; }
        public virtual DbSet<PAYS> PAYSSet { get; set; }
        public virtual DbSet<USERS> USERSSet { get; set; }
        public virtual DbSet<EXPENSES> EXPENSESSet { get; set; }
        public virtual DbSet<USERS_EXPENSES> USERS_EXPENSESSet { get; set; }
        public virtual DbSet<EXTRA_EXPENSES> EXTRA_EXPENSESSet { get; set; }
    }
}
