//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace drugaApka.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USERS_EXPENSES
    {
        public int ID_US_EXP { get; set; }
    
        public virtual USERS USERS { get; set; }
        public virtual EXPENSES EXPENSES { get; set; }
    }
}
